replicaCount: 2
image:
  repository: devangkubde88/webapp
  tag: 73
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
ingress:
  enabled: true
  alb:
    scheme: internet-facing
    targetType: ip
    path: /
